name: cicd

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run lint
      - run: npm run format

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps: 
      - uses: actions/checkout@v3 
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

  push:
    runs-on: ubuntu-latest
    needs: [release]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            jiridj/deliver-web:${{ github.ref_name }}
            jiridj/deliver-web:latest
          push: true
